version: '{build}'
skip_non_tags: true
image: Visual Studio 2022
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
    }

    dotnet build -c Release /p:SourceLinkCreate=true
test_script:
- cmd: dotnet test RapidSettings.Tests
artifacts:
- path: '**\*.nupkg'
  name: RapidSettings NuGet
deploy:
- provider: NuGet
  api_key:
    secure: FdK5+XAER1XV96x3jEFRe9kiHS5KJwe1EGBdQ00FW5YsnEYDABC96nUTxIkfGmLJ
  skip_symbols: true
  on:
    branch: master